name: Build Electron App for Windows

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: |
        npm install
        npm install electron-builder --save-dev

    - name: Build the app
      run: npm run build:win

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ElectronApp-win
        path: dist/*
